############# English navigation ##############

# main menu
[[main]]
weight = 1
url = "/"
name = "홈"
hasChildren = true

  [[main]]
  parent = "Home"
  weight = 1
  url = "homepage/list/"
  name = "List layout"

  [[main]]
  parent = "Home"
  weight = 2
  url = "homepage/grid/"
  name = "Grid layout"
  
[[main]]
weight = 3
url = "어바웃/"
name = "About"
  
[[main]]
weight = 4
url = "콘택트/"
name = "Contact"

[[main]]
weight = 5
url = "#"
name = "페이지들"
hasChildren = true

  [[main]]
  parent = "Pages"
  weight = 1
  url = "author/"
  name = "Author"
  
  [[main]]
  parent = "Pages"
  weight = 2
  url = "tags/"
  name = "Tags"
  
  [[main]]
  parent = "Pages"
  weight = 3
  url = "tags/photography/"
  name = "Tag Single"
  
  [[main]]
  parent = "Pages"
  weight = 4
  url = "categories/"
  name = "Category"
  
  [[main]]
  parent = "Pages"
  weight = 5
  url = "categories/lifestyle/"
  name = "Category Single"
  
  [[main]]
  parent = "Pages"
  weight = 6
  url = "elements/"
  name = "Elements"

############################# Footer Menu ########################
[[footer]]
weight = 1
url = "about/"
name = "어바웃"

[[footer]]
weight = 2
url = "author/"
name = "사용자"

[[footer]]
weight = 3
url = "privacy/"
name = "정책"

[[footer]]
weight = 4
url = "terms-conditions/"
name = "Terms & Conditions"