############# Korea navigation ##############

# main menu
[[main]]
weight = 1
url = "/"
name = "Home"

  
[[main]]
weight = 3
url = "about/"
name = "About"
  
[[main]]
weight = 4
url = "contact/"
name = "Contact"

[[main]]
weight = 5
url = "tags/"
name = "Tags"

[[main]]
weight = 6
url = "categories/"
name = "Category"



############################# Footer Menu ########################
[[footer]]
weight = 1
url = "about/"
name = "about"

[[footer]]
weight = 2
url = "author/"
name = "author"

[[footer]]
weight = 3
url = "privacy/"
name = "privacy"

[[footer]]
weight = 4
url = "terms-conditions/"
name = "Terms & Conditions"