############# Korea navigation ##############

# main menu

[[main]]
weight = 1
url = "/study/"
name = "Study"

[[main]]
weight = 2
url = "/sideproject/"
name = "SideProject"

[[main]]
weight = 3
url = "/favorite/"
name = "Favorite"
  
[[main]]
weight = 4
url = "/tool/"
name = "Tool"
#
[[main]]
weight = 5
url = "tags/"
name = "Tags"




############################# Footer Menu ########################
[[footer]]
weight = 1
url = "about/"
name = "about"

[[footer]]
weight = 2
url = "author/"
name = "author"

[[footer]]
weight = 3
url = "privacy/"
name = "privacy"

[[footer]]
weight = 4
url = "terms-conditions/"
name = "Terms & Conditions"